# Generated by Django 4.2.7 on 2024-04-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.product'),
            preserve_default=False,
        ),
    ]
