# Generated by Django 4.2.7 on 2024-04-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_discountmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
